theme: jekyll-theme-minimal
title: 'Weight tracking & monitoring app.'
description: 'BodyMetrica is a free and open-source application to monitor body weight, blood pressure and similar body metrics.'
name: 'BodyMetrica'